#!/usr/bin/env bash

set -euo pipefail

CACHE_LOCATION=${XDG_CACHE_HOME:-$HOME/.cache}
CACHE_DIR="$CACHE_LOCATION/dunex"

# parse command line
while [[ $# -gt 0 ]]; do
  case $1 in
    run)
      PKG="$2"
      PROG="${3:---}"

      if [ "$PROG" != "--" ]; then
	shift
      else
	PROG="$PKG"
      fi

      shift
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "Unknown option"
      exit 1
      ;;
  esac
done

PKG_DIR="$CACHE_DIR/$PKG"

# set up dune project
mkdir -p "$PKG_DIR"
cd "$PKG_DIR"
cat > dune-project <<EOF
(lang dune 3.21)
(package
  (name dummy)
  (allow_empty)
  (depends
    $PKG))
EOF
cat > dune-workspace <<EOF
(lang dune 3.21)
(pkg enabled)
EOF
dune build @pkg-install

cd - > /dev/null

# find binary and run
PKG_INSTALL_PATH=$(find "$PKG_DIR/_build/_private/default/.pkg" -name "${PKG}.*" -type d)
PROG_BIN="$PKG_INSTALL_PATH/target/bin/$PROG"
exec "$PROG_BIN" "$@"
