#!/usr/bin/env bash

set -euo pipefail

CACHE_LOCATION=${XDG_CACHE_HOME:-$HOME/.cache}
CACHE_DIR="$CACHE_LOCATION/dunex"

# parse command line
while [[ $# -gt 0 ]]; do
  case $1 in
    run)
      PKG="$2"
      PROG="${3:---}"

      if [ "$PROG" != "--" ]; then
	shift
      fi

      shift
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "Unknown option"
      exit 1
      ;;
  esac
done


VER=${PKG#*.}
PKG=${PKG%%.*}

if [ "$PROG" == "--" ]; then
  PROG="$PKG"
fi

PKG_DIR="$CACHE_DIR/$PKG"

# set up dune project
mkdir -p "$PKG_DIR"
cd "$PKG_DIR"

if [ "$PKG" = "$VER" ]; then
  # latest
  cat > dune-project <<-EOF
	(lang dune 3.21)
	(package
	  (name dummy)
	  (allow_empty)
	  (depends
	    $PKG))
	EOF
else
  cat > dune-project <<-EOF
	(lang dune 3.21)
	(package
	  (name dummy)
	  (allow_empty)
	  (depends
	    ($PKG (= $VER))))
	EOF
fi

cat > dune-workspace <<EOF
(lang dune 3.21)
(pkg enabled)
EOF
dune build @pkg-install

LOCKFILE=$(find "$PKG_DIR/_build/_private/default/.lock/dune.lock" -name "${PKG}.*" -type f)
DEPENDENCY_DIR=$(basename $LOCKFILE)
DEPENDENCY_DIR=${DEPENDENCY_DIR%.*}

cd - > /dev/null

# find binary and run
PKG_INSTALL_PATH=$(find "$PKG_DIR/_build/_private/default/.pkg" -name "${DEPENDENCY_DIR}-*" -type d)

PROG_BIN="$PKG_INSTALL_PATH/target/bin/$PROG"
exec "$PROG_BIN" "$@"
